cgen_version: '>=0.6.0'
template_version: 0.1.0

# questions: are variables that can be used in project generation.
questions:
  - name: DESCRIPTION
    type: string
    prompt: what are we building today

  - name: CREATE_SAMPLES
    type: bool
    prompt: generate sample questions
    default: true

  - name: GIT_BASE_URL
    type: string
    default: https://github.com/techdecaf

# executed by cgen after resolving variables, but before generating files
run_before: []
#  executed by cgen after generating the project
run_after:
  - git init
  - git add . && git commit -m "init"
  - 'echo ==== {{ToUpper .Name}} ===='
